import type { SocialProvider } from "@/lib/social-platforms";

export type SocialContentIdea = {
  platform: SocialProvider;
  topic: string;
  description: string;
  caption: string;
  hook: string;
  cta: string;
  hashtags: string[];
};

export const DEFAULT_SOCIAL_CONTENT: SocialContentIdea[] = [
  {
    platform: "instagram",
    topic: "Resume glow-up",
    description: "Show a before-and-after resume transformation for ATS clarity.",
    caption: "Your resume should make your value obvious in 6 seconds or less. Here's what we changed today.",
    hook: "Before/after resume glow-up",
    cta: "Try it on ResumeVaultGod.com",
    hashtags: ["#ResumeTips", "#ATS", "#JobSearch"],
  },
  {
    platform: "facebook",
    topic: "ATS myth busting",
    description: "Break down the most common ATS misconception and teach a better approach.",
    caption: "ATS is not the enemy - unclear resumes are. Here's how to make your resume easier to scan.",
    hook: "ATS myth vs reality",
    cta: "Build a stronger resume today",
    hashtags: ["#ResumeTips", "#JobSearch"],
  },
  {
    platform: "twitter",
    topic: "One-line bullet upgrade",
    description: "Teach the action + metric + outcome bullet formula.",
    caption: "Weak: helped with reports. Strong: cut reporting time by 40% and improved decision speed.",
    hook: "Upgrade your bullet points",
    cta: "Use ResumeVaultGod.com to rewrite yours",
    hashtags: ["#ResumeWriting", "#CareerAdvice"],
  },
  {
    platform: "tiktok",
    topic: "Job search confidence",
    description: "A quick pep talk on rejection and resilience.",
    caption: "Rejection is not your identity. It is just feedback that gets you closer to the right role.",
    hook: "Reframe rejection",
    cta: "Keep building with ResumeVaultGod.com",
    hashtags: ["#JobSearch", "#Motivation", "#CareerTok"],
  },
  {
    platform: "instagram",
    topic: "Cover letter hook",
    description: "Show three openings that sound human and specific.",
    caption: "A great cover letter opener sounds like a person, not a template. Here are 3 ways to start strong.",
    hook: "Three cover letter openings",
    cta: "Draft yours in ResumeVaultGod.com",
    hashtags: ["#CoverLetter", "#Hiring"],
  },
  {
    platform: "linkedin",
    topic: "Interview prep checklist",
    description: "Share the five interview questions every candidate should rehearse.",
    caption: "The best interview answers are rehearsed before the interview starts. Build your prep checklist early.",
    hook: "Your interview prep list",
    cta: "Use ResumeVaultGod.com to prepare",
    hashtags: ["#InterviewTips", "#JobSearch"],
  },
  {
    platform: "facebook",
    topic: "Networking DM template",
    description: "A simple outreach message that feels warm instead of awkward.",
    caption: "Networking gets easier when your message is short, specific, and respectful of someone's time.",
    hook: "A better DM template",
    cta: "Copy the format and personalize it",
    hashtags: ["#Networking", "#CareerAdvice"],
  },
  {
    platform: "instagram",
    topic: "Portfolio checklist",
    description: "Show the sections a portfolio needs to help land interviews.",
    caption: "A portfolio should prove your value fast. Make sure these 4 pieces are always included.",
    hook: "Portfolio must-haves",
    cta: "Build one with ResumeVaultGod.com",
    hashtags: ["#Portfolio", "#Branding"],
  },
  {
    platform: "linkedin",
    topic: "Career change story",
    description: "Reframe a pivot as a strength with transferable skills.",
    caption: "A pivot is not a detour when you can connect the dots clearly. Transferable skills tell that story well.",
    hook: "Turn your pivot into a strength",
    cta: "Shape the story with ResumeVaultGod.com",
    hashtags: ["#CareerChange", "#Growth"],
  },
  {
    platform: "tiktok",
    topic: "Resume mistake",
    description: "Explain why duty-only bullets underperform.",
    caption: "If your bullets sound like job duties only, recruiters may miss your impact. Let's fix that.",
    hook: "Stop writing duty-only bullets",
    cta: "Use ResumeVaultGod.com to improve them",
    hashtags: ["#ResumeHelp", "#CareerTok"],
  },
  {
    platform: "instagram",
    topic: "Action verb swap",
    description: "Show how to level up weak resume language.",
    caption: "Strong resume writing starts with stronger verbs. Small wording changes can change the whole vibe.",
    hook: "Swap weak verbs",
    cta: "Upgrade your resume today",
    hashtags: ["#ResumeTips", "#Writing"],
  },
  {
    platform: "linkedin",
    topic: "Job application strategy",
    description: "Teach a more intentional apply-follow-up workflow.",
    caption: "A good application strategy is not just volume. It is timing, targeting, and follow-up.",
    hook: "Apply smarter, not harder",
    cta: "Plan with ResumeVaultGod.com",
    hashtags: ["#JobSearchStrategy", "#Career"],
  },
  {
    platform: "reddit",
    topic: "Salary negotiation",
    description: "Give a concise negotiation tip with confidence.",
    caption: "You can be polite, prepared, and still ask for more. Negotiation is part of the process.",
    hook: "Negotiation without the panic",
    cta: "Practice with ResumeVaultGod.com",
    hashtags: ["#SalaryNegotiation", "#CareerAdvice"],
  },
  {
    platform: "youtube",
    topic: "Resume walkthrough video",
    description: "Record a short video showing how the resume builder improves a real resume.",
    caption: "A quick walkthrough can teach more than a static post. Show the resume transformation step by step.",
    hook: "Record the walkthrough",
    cta: "Build the video with ResumeVaultGod.com",
    hashtags: ["#YouTube", "#ResumeTips"],
  },
  {
    platform: "pinterest",
    topic: "Career cheat sheet pin",
    description: "Create a visual pin that bundles top resume mistakes and quick fixes.",
    caption: "Save this cheat sheet: 5 mistakes that weaken a resume and the fastest ways to fix them.",
    hook: "Make it visually useful",
    cta: "Pin it to your ResumeVaultGod board",
    hashtags: ["#Pinterest", "#ResumeTips"],
  },
  {
    platform: "facebook",
    topic: "Skills section",
    description: "Show how to prioritize relevant keywords.",
    caption: "Your skills section should match the job, not just look full. Relevance wins every time.",
    hook: "Skills that actually help",
    cta: "Audit yours with ResumeVaultGod.com",
    hashtags: ["#ResumeHelp", "#ATS"],
  },
  {
    platform: "linkedin",
    topic: "Personal branding",
    description: "Teach how the resume and online presence should match.",
    caption: "Your resume, LinkedIn, and portfolio should tell the same story with the same energy.",
    hook: "Build a consistent brand",
    cta: "Align it with ResumeVaultGod.com",
    hashtags: ["#PersonalBrand", "#LinkedIn"],
  },
  {
    platform: "instagram",
    topic: "Offer review",
    description: "Create a post that helps people evaluate offers beyond salary.",
    caption: "An offer is more than the paycheck. Scope, growth, flexibility, and team fit all matter too.",
    hook: "Review the full offer",
    cta: "Stay intentional with ResumeVaultGod.com",
    hashtags: ["#CareerAdvice", "#Offer"],
  },
  {
    platform: "facebook",
    topic: "Follow-up email",
    description: "Teach a short, respectful follow-up after interviews.",
    caption: "A strong follow-up email is short, grateful, and specific. No need to overdo it.",
    hook: "Follow-up formula",
    cta: "Draft one in ResumeVaultGod.com",
    hashtags: ["#InterviewPrep", "#Professionalism"],
  },
  {
    platform: "threads",
    topic: "30-day wrap-up",
    description: "Reflect on the month's progress and improvements.",
    caption: "Small improvements compound fast in a job search. Resume clarity, confidence, and consistency all matter.",
    hook: "The month in review",
    cta: "Keep the momentum going",
    hashtags: ["#CareerJourney", "#JobSearch"],
  },
];
